#!/usr/bin/env ruby
require 'fileutils'
require 'yaml'
require 'uri'
require 'net/http'
require 'json'

require 'pry'

FileUtils.chdir(__dir__)

tags ||= if ARGV.include?('--no-cache')
           []
         else
           url = URI('https://hub.docker.com/v2/repositories/madebytight/rude/tags?page_size=1000')
           response = Net::HTTP.get_response(url)

           JSON.parse(response.body)['results'].map { |i| i['name'] }
         end

YAML.load_file('versions.yml').each do |base_image, base_versions|
  base_versions.each do |base_version, versions|
    ruby_versions = versions['ruby']
    node_versions = versions['node']

    ruby_versions.each do |ruby_version, ruby_checksum|
      node_versions.each do |node_version, node_checksum|
        tag = "#{ruby_version}-#{node_version}-#{base_image}#{base_version}"

        if tags.include?(tag)
          puts "#{tag}: SKIP"
          next
        end

        puts "#{tag}: BUILD"

        system(
          {
            'BASE_IMAGE' => "#{base_image}:#{base_version}",
            'RUBY_VERSION' => ruby_version,
            'RUBY_CHECKSUM' => ruby_checksum,
            'NODE_VERSION' => node_version,
            'NODE_CHECKSUM' => node_checksum,
            'ALL_TAGS' => true.to_s
          },
          './create.sh'
        )

        puts "\n\n\n"
      end
    end
  end
end
